volumes:
  data:

services:
  app:
    build: .
    ports:
      - 4000:7777
    volumes:
      - data:/var/lib/docker/volumes/data/_data:rw
  mongodb:
    image: mongo
    volumes: 
      - data:/var/lib/docker/volumes/data/_data:rw

    